name: Publish new version upon tag commit
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: Deserialize signing certs
        run: |
          echo ${{ secrets.CERT_BASE64 }} | base64 --decode > cert.p7b
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > keystore.pfx
      - name: Build & create signed module
        run: >
          ./gradlew
          -Pversion=${{github.ref_name}}
          -PsignModule=true
          build
          signModule 
          --certFile=cert.p7b
          --certPassword="${{ secrets.CERT_PASSWORD }}"
          --keystoreFile=keystore.pfx
          --keystorePassword="${{ secrets.KEYSTORE_PASSWORD }}"
          --certAlias=ignition-extensions
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: build/Ignition-Extensions.modl
