name: Publish new version upon tag commit
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Deserialize signing certs
        run: |
          echo ${{ secrets.CERT_BASE64 }} | base64 --decode > cert.p7b
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > keystore.pfx
      - name: Build & create signed module
        run: >
          ./gradlew
          -Pversion=${{github.ref_name}}
          build
          signModule 
          --certFile=cert.p7b
          --certPassword="${{ secrets.CERT_PASSWORD }}"
          --keystoreFile=keystore.pfx
          --keystorePassword="${{ secrets.KEYSTORE_PASSWORD }}"
          --certAlias=ignition-extensions
      - name: Upload signed module
        uses: actions/upload-artifact@v3
        with:
          name: signed
          path: build/Ignition-Extensions.modl
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Download signed module
        uses: actions/download-artifact@v3
        with:
          name: signed
          path: artifacts
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: artifacts/*
