name: Run Gradle on PRs
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Decode signing secret to file
        run: |
          echo ${{ secrets.CERT_BASE64 }} | base64 --decode > cert.p7b
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > keystore.pfx
      - name: Execute Gradle build
        run: >
          ./gradlew
          -Pversion=${{github.ref_name}}
          build
          signModule
          --certFile=cert.p7b
          --certPassword="${{ secrets.CERT_PWD }}"
          --keystoreFile=keystore.pfx
          --keystorePassword="${{ secrets.KEYSTORE_PWD }}"
          --certAlias=ignition-extensions
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: signed
          path: build/Ignition-Extensions.modl
